module.exports = {
  title: 'My Project',
  tagline: 'Generated by CCR',
  url: 'http://localhost',
  baseUrl: '/',
  favicon: 'img/img.jpeg',

  onBrokenLinks: 'warn',           // temporarily warn
  onBrokenMarkdownLinks: 'warn',

  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          path: 'docs',
          routeBasePath: 'docs',   // URLs ab /docs/... honge
          sidebarPath: require.resolve('./docs/sidebars.js'),
        },
        blog: false,
      },
    ],
  ],

  themeConfig: {
    navbar: {
      
      items: [
        { to: '/my_project', label: 'My Project', position: 'left' },
        { to: 'docs/intro', label: 'Intro', position: 'left' },
        { to: 'docs/learning-outcomes', label: 'Learning Outcomes', position: 'left' },
      ],
    },
  },
};

// module.exports = {
//   title: 'My Project',
//   tagline: 'Generated by CCR',
//   url: 'http://localhost',
//   baseUrl: '/',
//   onBrokenLinks: 'throw',
//   onBrokenMarkdownLinks: 'warn',
//   favicon: 'img/favicon.ico',
//   presets: [
//     [
//       '@docusaurus/preset-classic',
//       {
//         docs: {
//           path: 'docs',
//           routeBasePath: '/',
//           sidebarPath: require.resolve('./sidebars.js'),
//         },
//         theme: {
//           customCss: require.resolve('./src/css/custom.css'),
//         },
//       },
//     ],
//   ],
// };
